version: "3.9"

services:
  chat-api:
    build: .
    container_name: chat_message_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./data.db
    restart: always
